[project]
name = "pydra_core"
version = "0.0.1"
description = "Python package for calculating hydraulic loads"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]
readme = "README.md"
license = "GPL-3.0"
license-file = "LICENSE"

[tasks]
# Installation
install = "pre-commit install"

# Docs
quartodoc-build = { cmd = "quartodoc build && rm objects.json", cwd = "docs" ,inputs = [
    "docs/_quarto.yml",
    "src/pydra_core",
    ],outputs = [
    "docs/reference/"
    ]}
quarto-preview = { cmd = "export QUARTO_PYTHON=python && quarto preview docs", depends_on = [
    "quartodoc-build",
] }
quarto-check = { cmd = "quarto check all", depends_on = ["quartodoc-build"] }
quarto-render = { cmd = "export QUARTO_PYTHON=python && quarto render docs --to html --execute", depends_on = [
    "quartodoc-build",
] }
docs = { depends_on = ["quarto-preview"] }


[feature.common.dependencies]
pandas ="*"
numpy ="*"
scipy ="*"
fiona ="*"
quarto = ">=1.5.57,<2"
quartodoc = ">=0.9.1,<0.10"
matplotlib = ">=3.9.3,<4"
ipykernel = ">=6.29.5,<7"
nbformat = ">=5.10.4,<6"
nbclient = ">=0.10.1,<0.11"
ruff = ">=0.8.1,<0.9"

[feature.common.pypi-dependencies]
pydra_core = { path = "src", editable = true }

[environments]
default = { features = ["common"] }


