name: Render and Publish Docs

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# You need these permissions to publish to GitHub pages
permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: pydra_core

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: pydra_core/pixi.toml
          pixi-version: "latest"

      - name: Check Quarto installation and all engines
        working-directory: pydra_core
        run: pixi run quarto-check

      - name: Render Quarto Project
        run: pixi run quarto-render

      # - name: Publish Quarto Project
      #   if: github.ref == 'refs/heads/main'
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: pydra_core/docs/docs
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
