name: Run Pytest

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# You need these permissions to publish to GitHub pages
permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: continu_inzicht

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: continu_inzicht/pixi.toml
          pixi-version: "latest"

      - name: Copy github secrets to environment variables files
        working-directory: continu_inzicht
        run: |
            touch .env
            echo host=${{ secrets.HOST }} >> .env
            echo database=${{ secrets.DATABASE }} >> .env
            echo port=${{ secrets.PORT }} >> .env
            echo password=${{ secrets.PASSWORD }} >> .env
            echo user=${{ secrets.USER }} >> .env
            echo schema=${{ secrets.SCHEMA }} >> .env
            cat .env

      - name: Run Pytests
        working-directory: continu_inzicht
        run: pixi run pytest --cov

        # later maybe upload to a coverage site, e.g.:
      #   run: pytest --cov --cov-report=xml
      #   shell: bash -l {0}
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     use_oidc: true
